name: implicitly_animated_reorderable_list
description: A Flutter `ListView` that implicitly calculates the changes between two lists using the `MyersDiff` algorithm and animates between them for you. Optionally you can use the `ImplicitlyAnimatedReorderableList`, that can reorder its items with fully custom animations.
version: 0.1.0
author: Bendix Mahnke
homepage: https://github.com/BendixMa/implicitly_animated_reorderable_list/tree/master/example/lib/ui

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: